<div id="edit-content" class="seotoaster container">
    <?php
        $draftOrLive = $this->toasterDraftorlive(array(
            'published'        => $this->contentForm->getPublished(),
            'publishAt'        => $this->publishingDate,
            'onselectCallback' => null
        ));

        echo $this->partial(
            'admin' . DIRECTORY_SEPARATOR . '_header.phtml',
            array(
                'innerHeaderHtml'     => $draftOrLive,
                'pluginsSpace'        => $this->pluginsEditorTop,
                'helpSection'         => $this->helpSection,
                'localizationSection' => $this->localizationSection
            )
        );
    ?>
    <div class="content-footer">
        <div class="grid_8 above-editor-links">
            <form id="frm_content" action="<?php echo $this->url(); ?>" method="post" enctype="application/x-www-form-urlencoded">
                <?php echo $this->contentForm->getElement('content'); ?>
                <?php echo $this->contentForm->getElement('containerType'); ?>
                <?php echo $this->contentForm->getElement('containerName'); ?>
                <?php echo $this->contentForm->getElement('pageId'); ?>
                <?php echo $this->contentForm->getElement('containerId'); ?>
            </form>
        </div>

        <?php $this->tabPane('tabs', $this->render('backend/content/righttoolbar.phtml'), array('title' => $this->translate('Content')));?>
        <?php $this->tabPane('tabs', '', array('title' => $this->translate('Widgets')));?>

        <?php if(isset($this->pluginsTabs) && is_array($this->pluginsTabs)): ?>
            <?php foreach($this->pluginsTabs as $tabData): ?>
                <?php $this->tabPane('tabs', $tabData['content'], array('title' => $this->translate($tabData['title'])));?>
            <?php endforeach; ?>
        <?php endif; ?>

        <?php echo $this->tabContainer('tabs', array(), array('class' => 'grid_4 alpha tabs tabs-gray'));?>
        <input type="hidden" id="reset_css" value="<?php echo $this->linkResetCss; ?>" />
        <input type="hidden" id="content_css" value="<?php echo $this->linkContentCss; ?>" />
    </div>

    <div class="footer grid_12">
        <?php echo $this->contentForm->getElement('submit'); ?>
    </div>
    <script>
        var containerId = $('#containerId').val();
        var lang        = '<?php echo $this->localizationSection; ?>';
        var href        = location.href;

        if(href.indexOf('lang/')){
            href = href.substring(0, href.indexOf('/lang'));
        }

        $('[name="localization"]').on('change', function(){
            var $this         = $(this);
            var currentLang   = $this.data('lang');
            var ajaxUrl       = href + '/lang/' + lang;
            var newFormAction = href + '/lang/' + currentLang;
            showConfirm('Save changes?', function(){
                $.ajax({
                    url     : ajaxUrl,
                    type    : 'POST',
                    data    : $('#frm-page').serialize(),
                    success : function(response){
                        location.href = newFormAction;
                    }
                });
                lang = currentLang;
            }, function(){
                location.href = newFormAction;
                lang = currentLang;
            });
        });
    </script>
</div>
<?php
    $this->headScript()
        ->appendFile($this->websiteUrl . 'system/js/external/tinymce/tinymce.min.js')
        ->appendFile($this->websiteUrl . 'system/js/internal/tinymceInit.js')
        ->appendFile($this->websiteUrl . 'system/js/internal/content.min.js');
?>