<div class="seotoaster container">
	<?php echo $this->partial(
        'admin' . DIRECTORY_SEPARATOR . '_header.phtml',
        array(
            'innerHeaderHtml'     => 'Edit header',
            'helpSection'         => $this->helpSection,
            'localizationSection' => $this->localizationSection
        )
    ); ?>
    <?php
        $this->contentForm->setAction($this->url());
        echo $this->contentForm;
//        <input type="hidden" name="secureToken" class="secureToken" value="<?php echo $this->secureToken;?>" />
    ?>
</div>