<?php if (!empty($this->headerText) || !empty($this->innerHeaderHtml)): ?>
<div class="header">
<?php endif;?>

<div class="closebutton">
	<?php
    if($this->localizationSection === NULL){
        $this->localizationSection = true;
    }
    if(isset($this->localizationSection)){
        $website      = Zend_Controller_Action_HelperBroker::getStaticHelper('website');
        $configHelper = Zend_Controller_Action_HelperBroker::getStaticHelper('config');
        $localization = explode(',', $configHelper->getConfig('localization'));
        if ($localization) {
            $contentLocalization = '<div class="btn-set">';

            $checked = !is_string($this->localizationSection) ? 'checked' : '';
            $contentLocalization .= '<input id="lang" type="radio" class="processed" name="localization" ' .  $checked . ' data-lang="">'
                . '<label class="fade p5px pointer" for="lang">'
                    . '<img alt="' . $configHelper->getConfig('language') . '" class="lang-select" src="' . $website->getUrl() . 'system/images/flags/' . $configHelper->getConfig('language') . '.png" border="0">'
                . '</label>';

            foreach ($localization as $lang){
                $checked = $this->localizationSection === $lang ? 'checked' : '';
                $contentLocalization .= '<input id="lang-' . $lang . '" type="radio" class="processed" data-lang="' . $lang . '" name="localization"' .  $checked . '>'
                     . '<label class="fade p5px pointer" for="lang-' . $lang . '">'
                       . '<img alt="' . $lang . '" class="lang-select" src="' . $website->getUrl() . 'system/images/flags/' . $lang . '.png" border="0">'
                     . '</label>';
            }
            $contentLocalization .= '</div>';
            echo $contentLocalization;
        }
    } ?>
	<?php if(isset($this->helpSection)){
        echo $this->toasterHelp($this->helpSection, $this->hashMap);
    } ?>
    <a class="close ticon-close" href="javascript:;" title="<?php echo $this->translate('Close'); ?>"></a>
</div>

<?php echo (isset($this->headerText) ? $this->translate($this->headerText) : ''); ?>
<?php if(isset($this->innerHeaderHtml) && $this->innerHeaderHtml): ?>
	<?php echo $this->innerHeaderHtml; ?>
<?php endif; ?>

<?php if(isset($this->pluginsSpace) && is_array($this->pluginsSpace) && !empty ($this->pluginsSpace)): ?>
	<div class="pluginspace">
		<?php foreach($this->pluginsSpace as $pluginEditorTop): ?>
			<div class="<?php echo (isset($pluginEditorTop['title']) ? $pluginEditorTop['title']: ''); ?>">
				<?php echo(isset($pluginEditorTop['code']) ? $pluginEditorTop['code'] : ''); ?>
			</div>
		<?php endforeach; ?>
	</div>
<?php endif; ?>

<?php if (!empty($this->headerText) || !empty($this->innerHeaderHtml)): ?>
</div>
<?php endif;?>